title: Aude Dupont # your name (or website title) here
logo: "/images/profile.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with a master's degree in Computer Engineering and Management specialist focus on Artificial Intelligence and Decision Aid from UMons Polytechnic Faculty. Currently Functional Analyst at Smals, focusing on ETL architecture and reporting. 
  <br><br>
  Someone said "Maybe stories are just data with a soul". Well great, I'm not good at telling stories, but I'm good at data. 
  <br><br>
  <a href="https://www.linkedin.com/in/audedpt/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-EL8PNFDLYZ # your Google Analytics tracking ID here
